### PR TITLE
Fix wrong check from #901

### LINKED ISSUE #900: Intermittent failure while loading token in EKS with service accounts
I'm running a Symfony app in EKS, and I'm using SQS with Messenger + this lib.

I'm having small clusters of failures at long intervals with 403 responses from the SQS APIs:
```
HTTP 403 returned for "https://sqs.eu-central-1.amazonaws.com/".

Code:    AccessDenied
Message: Access to the resource https://sqs.eu-central-1.amazonaws.com/ is denied.
Type:    Sender
Detail:
```
I've dig into the logs, and I've found this warning:
```
php.WARNING: Warning: file_get_contents(/var/run/secrets/eks.amazonaws.com/serviceaccount/token): failed to open stream: No such file or directory {"exception":"[object] (ErrorException(code: 0): Warning: file_get_contents(/var/run/secrets/eks.amazonaws.com/serviceaccount/token): failed to open stream: No such file or directory at /var/www/my-project/vendor/async-aws/core/src/Credentials/WebIdentityProvider.php:92)"} []
```
So I've traced down the issue to something that happened on the official SDK too: https://github.com/aws/aws-sdk-php/issues/2014

Basically, it's a combination of:
 * tokens are short lived
 * EKS replaces tokens on-the-fly
 * PHP's realpath cache gets in the way...

... so you get brief intervals in which you try to read the old, now missing token.

In the offical SDK, the issue was mitigated by clearing the cache in a precise and ordered way of the following paths:
```
/var/run/secrets/eks.amazonaws.com/serviceaccount/..data/token
/var/run/secrets/eks.amazonaws.com/serviceaccount/..data
/var/run/secrets/eks.amazonaws.com/serviceaccount/token
```
in this PR: https://github.com/aws/aws-sdk-php/pull/2043

Can we apply the same logic here too?

### PR DESCRIPTION
**Pull request by Jean85**
This fixes #900, again.

Sorry for getting it wrong the first time around.

### CODE REVIEW

File: src/Core/src/Credentials/WebIdentityProvider.php [hunk 1]
```diff
@@ -128,14 +128,18 @@ private function getCredentialsFromRole(string $roleArn, string $tokenFile, ?str
      */
     private function getTokenFileContent(string $tokenFile): string
     {
-        if (!file_exists($tokenFile)) {
-            $tokenDir = \dirname($tokenFile);
-            $tokenLink = readlink($tokenFile);
-            clearstatcache(true, $tokenDir . \DIRECTORY_SEPARATOR . $tokenLink);
-            clearstatcache(true, $tokenDir . \DIRECTORY_SEPARATOR . \dirname($tokenLink));
-            clearstatcache(true, $tokenFile);
+        $token = @file_get_contents($tokenFile);
```
Comment (Jean85) [inline src/Core/src/Credentials/WebIdentityProvider.php:131]: `@` is to suppress warning in the exact case of hitting the realpath cache with the wrong valued.

**Review by Nyholm — APPROVED** [review]
Im happy you verified and checked.

File: src/Core/src/Credentials/WebIdentityProvider.php [hunk 2]
```diff
@@ -128,14 +128,18 @@ private function getCredentialsFromRole(string $roleArn, string $tokenFile, ?str
...
+            return $token;
         }
 
+        $tokenDir = \dirname($tokenFile);
+        $tokenLink = readlink($tokenFile);
+        clearstatcache(true, $tokenDir . \DIRECTORY_SEPARATOR . $tokenLink);
+        clearstatcache(true, $tokenDir . \DIRECTORY_SEPARATOR . \dirname($tokenLink));
+        clearstatcache(true, $tokenFile);
+
         if (false === $token = file_get_contents($tokenFile)) {
```
Comment (jderusse) [inline src/Core/src/Credentials/WebIdentityProvider.php:143]: shouldn't it be `@file_get_contents` here?

**Review by jderusse — APPROVED** [review]
Huge thank you for the investigation and the quick fix

File: src/Core/src/Credentials/WebIdentityProvider.php (hunk 2 above)
Comment (Jean85) [reply src/Core/src/Credentials/WebIdentityProvider.php:143]: I preferred to have the warning here anyway, since it helped me a lot debugging this regression.

IIRC, we get here only if we get the token file path from the env variable, so we shouldn't arrive to this point if there's no token to start with.

**Comment by Nyholm** [comment]
Cool cool cool. Thank you for the fix. 

Can you confirm that this fix is working for you?

**Comment by Jean85** [comment]
I've deployed it in prod. I'll report back in a few days to be sure, since it didn't happen continuously.

**Comment by Nyholm** [comment]
How does it look? Did this PR fix the issue?

**Comment by Jean85** [comment]
Confirming here too as in #906: this works! :+1:
