### PR TITLE
Differentiate empty list from no list

### LINKED ISSUE #667: [DynamobDB] Deal with empty List
Hello !

Currently it seems impossible to send an empty list.

Here is my operation :
```
 $this->dynamoDbClient->updateItem([
                'TableName' => 'reservations_tenant',
                'Key' => [
                    'user_id' => ['S' => 'myUser'],
                ],
                'UpdateExpression' => 'SET reservation_ids = list_append(if_not_exists(reservation_ids, :emptyList), :newReservationId)',
                'ExpressionAttributeValues' => [
                    ':newReservationId' => ['L' => [['S' => $tenant->reservationId()]]],
                    ':emptyList' => ['L' => []],
                ],
            ])
```

But it sends : 
```
-body: AsyncAws\Core\Stream\StringStream {#2154
           -content: "{"TableName":"reservations_tenant","Key":{"user_id":{"S":"lala"}},"UpdateExpression":"SET reservation_ids = list_append(if_not_exists(reservation_ids, :emptyList), :newReservationId)","ExpressionAttributeValues":{":newReservationId":{"L":[{"S":"TJFXHZI-4"}]},":emptyList":[]}}"
           -lengthCache: null
         }
```

Where it should send:
`"emptyList": ["L" => []]`

Without i get from AWS:
```
SerializationException
Message: Unrecognized collection type class com.amazonaws.dynamodb.v20120810.AttributeValue
```

I am missing something ?

Thanks

### PR DESCRIPTION
**Pull request by tyx**
Try to fix #667

### CODE REVIEW

**Comment by Nyholm** [comment]
Thank you. 

I think #667 is an issue we should solve. However, note that the clients are generated. Which means that we cannot edit this code directly. We need to modify the code generator. 

https://async-aws.com/contribute/

**Comment by tyx** [comment]
Yes of course ! I just wanted to show you quickly my suggestion before diving in code generator 😅

File: src/Service/DynamoDb/src/ValueObject/AttributeValue.php [hunk 1]
```diff
@@ -77,7 +77,7 @@ public function __construct(array $input)
         $this->NS = $input['NS'] ?? [];
         $this->BS = $input['BS'] ?? [];
         $this->M = array_map([AttributeValue::class, 'create'], $input['M'] ?? []);
-        $this->L = array_map([AttributeValue::class, 'create'], $input['L'] ?? []);
+        $this->L = array_key_exists('L', $input) ? array_map([AttributeValue::class, 'create'], $input['L']) : null;
```
Comment (jderusse) [inline src/Service/DynamoDb/src/ValueObject/AttributeValue.php:80]: should be isset or you should handle null value

File: src/Service/DynamoDb/src/ValueObject/AttributeValue.php [hunk 2]
```diff
@@ -110,7 +110,7 @@ public function getBS(): array
      */
     public function getL(): array
     {
-        return $this->L;
+        return $this->L ?? [];
```
Comment (jderusse) [inline src/Service/DynamoDb/src/ValueObject/AttributeValue.php:113]: return type should be ?array as other optional option

**Comment by Nyholm** [comment]
> but that will be a BC break for getters.

But what getters are we talking about? I believe `$s3->listFiles()` should be an empty array an not null. But in this scenario with DynamoDb it should be null. Maybe it is a way to define/differentiate those. 

Im fine with BC breaks in DynamoDB btw.

**Comment by jderusse** [comment]
I'm talking about all getters on Input and ValueObjects:

If we change it this in generator, it will impact all services.

```diff
 $i = new SendEmailRequest([]);
-var_dump($i->ReplyToAddresses()): // array()
+var_dump($i->ReplyToAddresses()): // null
```

**Comment by tyx** [comment]
Hi !

I updated the PR with CodeGenerator changes.

I tried to use the generated code on my project and it works for my usecase.

I just failled to change the getter return type to `array|null` if one of you could help !

Let me know if anything could be improved

File: src/Service/CloudFormation/src/ValueObject/RollbackConfiguration.php [hunk 3]
```diff
@@ -23,7 +23,7 @@ final class RollbackConfiguration
      */
     public function __construct(array $input)
     {
-        $this->RollbackTriggers = array_map([RollbackTrigger::class, 'create'], $input['RollbackTriggers'] ?? []);
+        $this->RollbackTriggers = isset($input['RollbackTriggers']) ? array_map([RollbackTrigger::class, 'create'], $input['RollbackTriggers']) : null;
```
Comment (Nyholm) [inline src/Service/CloudFormation/src/ValueObject/RollbackConfiguration.php:26]: Hm.. 

```php
$x = new RollbackConfiguration();
$x->getRollbackTriggers(); // will throw type error
```

**Comment by Nyholm** [comment]
Am I correct when I say that it is only DynamoDb that need to make a difference between null and empty list?

If so, could we add a special feature flag in manifest.json?

**Comment by tyx** [comment]
I should admit I really don't know.

**Comment by jderusse** [comment]
> Am I correct when I say that it is only DynamoDb that need to make a difference between null and empty list?

I don't think so. I guess we are lucky because in other services AWS (or we) converts null into empty array.

If we want keeping BC, we may fallback to empty array in getter like @tyx did in the first implementation

File: src/CodeGenerator/src/Generator/RequestSerializer/RestJsonSerializer.php [hunk 4]
```diff
@@ -171,18 +171,32 @@ private function dumpArrayList(string $output, string $input, string $contextPro
         $memberShape = $shape->getMember()->getShape();
 
         return strtr('
-            $index = -1;
-            foreach (INPUT as $listValue) {
-                $index++;
-                MEMBER_CODE
+            if (null !== INPUT) {
```
Comment (jderusse) [inline src/CodeGenerator/src/Generator/RequestSerializer/RestJsonSerializer.php:174]: This not needed (or not the right implementation). None of other `dump*` method performs such check because, this should have been done before.

File: src/CodeGenerator/src/Generator/RequestSerializer/RestJsonSerializer.php [hunk 5]
```diff
@@ -171,18 +171,32 @@ private function dumpArrayList(string $output, string $input, string $contextPro
...
+                $index = -1;
+                INIT_CODE
```
Comment (jderusse) [inline src/CodeGenerator/src/Generator/RequestSerializer/RestJsonSerializer.php:176]: hmm.  This is alway `$payload = [];` right? no need for an other extra method

File: src/Service/CloudFormation/src/ValueObject/RollbackConfiguration.php (hunk 3 above)
Comment (jderusse) [reply src/Service/CloudFormation/src/ValueObject/RollbackConfiguration.php:26]: indeed. We should either change the return typehint of getter (BC break) 
Or fallback to empty array

File: src/CodeGenerator/src/Generator/RequestSerializer/RestJsonSerializer.php (hunk 4 above)
Comment (jderusse) [reply src/CodeGenerator/src/Generator/RequestSerializer/RestJsonSerializer.php:174]: Got it, you should remove at line 62
```diff
-if ($shape instanceof ListShape || $shape instanceof MapShape) {
+if ($shape instanceof MapShape) {
   $body = 'MEMBER_CODE';
   $inputElement = '$this->' . $member->getName();
 }

File: src/CodeGenerator/src/Generator/RequestSerializer/RestJsonSerializer.php [hunk 6]
```diff
@@ -171,18 +171,32 @@ private function dumpArrayList(string $output, string $input, string $contextPro
...
                 'INPUT' => $input,
+                'INIT_CODE' => $this->dumpArrayInit($output, $memberShape),
                 'MEMBER_CODE' => $memberCode = $this->dumpArrayElement(sprintf('%s[$index]', $output), '$listValue', $contextProperty, $memberShape, true),
             ]);
     }
 
+    private function dumpArrayInit(string $output, Shape $shape)
+    {
+        switch (true) {
+            case $shape instanceof StructureShape && 'AttributeValue' === $shape->getName():
```
Comment (jderusse) [inline src/CodeGenerator/src/Generator/RequestSerializer/RestJsonSerializer.php:193]: remove specific code `AttributeValue`

File: src/CodeGenerator/src/Generator/RequestSerializer/RestJsonSerializer.php (hunk 5 above)
Comment (tyx) [reply src/CodeGenerator/src/Generator/RequestSerializer/RestJsonSerializer.php:176]: I created the other method to ensure not doing this init everywhere as it break many tests.

Comment (jderusse) [reply src/CodeGenerator/src/Generator/RequestSerializer/RestJsonSerializer.php:176]: what if the test were wrong before?..

File: src/CodeGenerator/src/Generator/RequestSerializer/RestJsonSerializer.php (hunk 6 above)
Comment (tyx) [reply src/CodeGenerator/src/Generator/RequestSerializer/RestJsonSerializer.php:193]: Same here. I restricted to reduce side effect and broken test.

I will revert it to let you have a look on broken test?

File: src/CodeGenerator/src/Generator/RequestSerializer/RestJsonSerializer.php (hunk 5 above)
Comment (tyx) [reply src/CodeGenerator/src/Generator/RequestSerializer/RestJsonSerializer.php:176]: Many are correct, for example. in DynamoDB, only List could be sent empty. Not Set (like SS, NS or BS).

**Comment by tyx** [comment]
> > Am I correct when I say that it is only DynamoDb that need to make a difference between null and empty list?
> 
> I don't think so. I guess we are lucky because in other services AWS (or we) converts null into empty array.

And currently, empty array are never sent. And I have no idea what it would mean to send all of them. At least in DynamoDB, only `List` could be sent empty, not `Set` (I don't know for `Map`)

File: src/CodeGenerator/src/Generator/RequestSerializer/RestJsonSerializer.php (hunk 5 above)
Comment (tyx) [reply src/CodeGenerator/src/Generator/RequestSerializer/RestJsonSerializer.php:176]: We could introduce a specific Shape like SetShape and keep ListShape for real list ? To allow making things differently

**Comment by jderusse** [comment]
> And currently, empty array are never sent

Thats should still be the case, unless people creates objects with explicit empty array, the arrays should be initialized with null, not beeing sent.

**Comment by tyx** [comment]
Ok you're right. I tried to not change everything, but I guess I have no choice.

Here is the PR updated and tests are green (in local).

Still the getter issue I need to update

**Comment by tyx** [comment]
Ok, here it is !

I found how to handle null value.

File: src/CodeGenerator/src/Generator/RequestSerializer/RestJsonSerializer.php [hunk 7]
```diff
@@ -172,17 +169,29 @@ private function dumpArrayList(string $output, string $input, string $contextPro
...
+                'INIT_CODE' => $this->dumpArrayInit($output, $memberShape),
                 'MEMBER_CODE' => $memberCode = $this->dumpArrayElement(sprintf('%s[$index]', $output), '$listValue', $contextProperty, $memberShape, true),
             ]);
     }
 
+    private function dumpArrayInit(string $output, Shape $shape)
+    {
+        switch (true) {
+            case $shape instanceof StructureShape:
+                return strtr('$payloadOUTPUT = [];', [
```
Comment (jderusse) [inline src/CodeGenerator/src/Generator/RequestSerializer/RestJsonSerializer.php:189]: I style don't get why we initialize the array when children is a structure, and we don't do it for map, list, scalar...

File: src/CodeGenerator/src/Generator/InputGenerator.php [hunk 8]
```diff
@@ -111,23 +111,21 @@ public function generate(Operation $operation): ClassName
...
-                    $constructorBody .= strtr('$this->NAME = $input["NAME"] ?? [];' . "\n", ['NAME' => $member->getName()]);
+                    $constructorBody .= strtr('$this->NAME = $input["NAME"] ?? null;' . "\n", ['NAME' => $member->getName()]);
                 }
             } elseif ($memberShape instanceof MapShape) {
                 $mapKeyShape = $memberShape->getKey()->getShape();
                 if (!empty($mapKeyShape->getEnum())) {
                     $this->enumGenerator->generate($mapKeyShape);
                 }
                 $mapValueShape = $memberShape->getValue()->getShape();
-                $nullable = false;
```
Comment (jderusse) [inline src/CodeGenerator/src/Generator/InputGenerator.php:130]: I wonder if it make sens to also deal with Map

File: src/Core/src/Sts/Input/AssumeRoleRequest.php [hunk 9]
```diff
@@ -163,9 +163,9 @@ public function getPolicy(): ?string
     }
 
     /**
-     * @return PolicyDescriptorType[]
+     * @return PolicyDescriptorType[]|null
      */
-    public function getPolicyArns(): array
+    public function getPolicyArns(): ?array
```
Comment (jderusse) [inline src/Core/src/Sts/Input/AssumeRoleRequest.php:168]: sadly that's a BC break :(

File: src/Service/CloudWatchLogs/src/Input/PutLogEventsRequest.php [hunk 10]
```diff
@@ -162,9 +162,13 @@ private function requestBody(): array
             throw new InvalidArgument(sprintf('Missing parameter "logStreamName" for "%s". The value cannot be null.', __CLASS__));
         }
         $payload['logStreamName'] = $v;
+        if (null === $v = $this->logEvents) {
+            throw new InvalidArgument(sprintf('Missing parameter "logEvents" for "%s". The value cannot be null.', __CLASS__));
```
Comment (jderusse) [inline src/Service/CloudWatchLogs/src/Input/PutLogEventsRequest.php:166]: Is it a BC break?.. The field is required, but previously AsyncAws replaced null by empty array.

File: src/Service/DynamoDb/tests/Integration/DynamoDbClientTest.php [hunk 11]
```diff
@@ -262,6 +262,28 @@ public function testUpdateItem(): void
         self::assertEquals(200, $result->info()['status']);
     }
 
+    public function testUpdateItemWithList(): void
```
Comment (jderusse) [inline src/Service/DynamoDb/tests/Integration/DynamoDbClientTest.php:265]: thanks for this!!

File: src/CodeGenerator/src/Generator/RequestSerializer/RestJsonSerializer.php (hunk 7 above)
Comment (tyx) [reply src/CodeGenerator/src/Generator/RequestSerializer/RestJsonSerializer.php:189]: After latest change, it could be useless now, I will give it a try !

File: src/Core/src/Sts/Input/AssumeRoleRequest.php (hunk 9 above)
Comment (tyx) [reply src/Core/src/Sts/Input/AssumeRoleRequest.php:168]: Yes for now, I don't implement the first solution to avoid BC break. But it stills possible

File: src/CodeGenerator/src/Generator/RequestSerializer/RestJsonSerializer.php (hunk 7 above)
Comment (tyx) [reply src/CodeGenerator/src/Generator/RequestSerializer/RestJsonSerializer.php]: Ok good catch, I just removed this stuff

**Comment by Nyholm** [comment]
I think the easiest way to move forward is to add feature flags in the manifest json. 

So for each API we can toggle if we should do `?array` or not. So for our 4 APIs that are tagged with 1.0, we keep the old behavior, but we can update DynamoDb (and others if we want) with this new behavior.

**Comment by tyx** [comment]
Like this ?
```json
{
    "DynamoDb": {
            "features": {
                "empty_array": true
            }
    }
}
```

File: src/Core/src/Sts/Input/AssumeRoleRequest.php [hunk 12]
```diff
@@ -186,9 +186,9 @@ public function getSerialNumber(): ?string
     }
 
     /**
-     * @return Tag[]
+     * @return Tag[]|null
      */
-    public function getTags(): array
+    public function getTags(): ?array
```
Comment (jderusse) [inline src/Core/src/Sts/Input/AssumeRoleRequest.php:191]: At first I thought that `?array` was the right way to handle getters. It's consistent with all other getter.

But in that precise example, I think that'll reduce DX. leading to
```
if ($request->getTags() !== null) {
  foreach ($request->getTags() as $tag) {}
}

// or
foreach ($request->getTags() ?? [] as $tag) {}
```

I think we can safetly always fallback to `[]` , and change the signature of this getter to `array`.
If one day we change our mind, we'll be able to add a deprecation notice and change the behavior.

In DynamoDb, is it important to distinguished null from empty array (the original bug)?
- if yes, we should go with feature flag as suggested by @Nyholm (only on really required properties)
- if no, we just fallback to ` ?? []` everywhere

**Comment by jderusse** [comment]
More something like this
```
{
    "DynamoDb": {
            "features": {
                "empty_array": [
                   'AttributeValue.NS', // ShapeName "." MemberName
                ]
            }
    }
}
```

File: src/Core/src/Sts/Input/AssumeRoleRequest.php (hunk 12 above)
Comment (tyx) [reply src/Core/src/Sts/Input/AssumeRoleRequest.php:191]: > In DynamoDb, is it important to distinguished null from empty array (the original bug)?

from what I've seen of it, it's not a problem. Getter can continue to return empty array.

**Comment by Nyholm** [comment]
Yeah. Or `s/empty_array/nullable_array/`

File: src/Core/src/Sts/Input/AssumeRoleRequest.php (hunk 12 above)
Comment (jderusse) [reply src/Core/src/Sts/Input/AssumeRoleRequest.php:191]: great, feature flag behavior is not (yet) needed. internal call distinguish null from empty, but external signature always return array.

what do you think @Nyholm

Comment (Nyholm) [reply src/Core/src/Sts/Input/AssumeRoleRequest.php:191]: Lets try to use the fallback and we will see =)

Comment (tyx) [reply src/Core/src/Sts/Input/AssumeRoleRequest.php]: Just updated the PR with the fallback to array.

I still have some fix needed on 3 S3 operations but main modification is here.

**Comment by tyx** [comment]
phpstan failure seems unrelated

File: src/CodeGenerator/src/Generator/InputGenerator.php [hunk 13]
```diff
@@ -182,12 +185,13 @@ public function generate(Operation $operation): ClassName
             if ($member->isRequired()) {
                 $property->addComment('@required');
             }
+
             // the "\n" helps php-cs-fixer to with potential wildcard in parameterType
-            $property->addComment("\n@var " . ($nullable ? 'null|' : '') . $parameterType);
+            $property->addComment("\n@var " . ($propertyNullable ? 'null|' : '') . $parameterType);
```
Comment (jderusse) [inline src/CodeGenerator/src/Generator/InputGenerator.php:190]: looks like `$propertyNullable` is always true

File: src/CodeGenerator/src/Generator/ObjectGenerator.php [hunk 14]
```diff
@@ -254,13 +253,21 @@ private function addProperties(StructureShape $shape, ClassType $class, PhpNames
...
+            } else {
+                $method->setBody($deprecation . strtr('
+                        return $this->NAME ?? [];
+                    ', [
+                    'NAME' => $member->getName(),
+                ]));
+            }
 
-            $nullable = $nullable ?? !$member->isRequired();
+            $nullable = ($nullable ?? !$member->isRequired()) && $getterSetterNullable;
```
[the remark this answers is not in the document]
Comment (tyx) [reply src/CodeGenerator/src/Generator/ObjectGenerator.php:270]: we still have one nullable use : https://github.com/async-aws/aws/blob/master/src/CodeGenerator/src/Generator/ObjectGenerator.php#L245

[the remark this answers is not in the document]
Comment (tyx) [reply src/CodeGenerator/src/Generator/ObjectGenerator.php:270]: in fact we still need to distinguish List/Map nullable (to use Null Coalesce in getter) from current nullable (to indicate null in return phpdoc).

Or I miss something ? (monday morning so it could be possible :D)

File: .github/workflows/static.yml [hunk 15]
```diff
@@ -20,7 +20,9 @@ jobs:
           composer update --no-interaction --prefer-dist --optimize-autoloader
 
       - name: PHPStan
-        uses: OskarStark/phpstan-ga@0.12.23
+        uses: OskarStark/phpstan-ga@latest
```
Comment (shouze) [inline .github/workflows/static.yml:23]: :crossed_fingers:

Comment (shouze) [reply .github/workflows/static.yml:23]: related to https://github.com/OskarStark/phpstan-ga/pull/29

File: src/CodeGenerator/src/Generator/ObjectGenerator.php (hunk 14 above)
[the remark this answers is not in the document]
Comment (tyx) [reply src/CodeGenerator/src/Generator/ObjectGenerator.php:270]: To make is easier to read I could set nullable and getterSetterNullable in List/Map block

[the remark this answers is not in the document]
Comment (tyx) [reply src/CodeGenerator/src/Generator/ObjectGenerator.php]: I updated with my latest proposal

**Comment by tyx** [comment]
rebased to get phpstan fix ;)

**Comment by tyx** [comment]
I'm done here !

Let me know if anything need to be changed.

File: src/CodeGenerator/src/Generator/RequestSerializer/QuerySerializer.php [hunk 16]
```diff
@@ -68,9 +68,6 @@ public function generateRequestBuilder(StructureShape $shape): array
                 }
                 MEMBER_CODE';
                 $inputElement = '$v';
-            } elseif ($shape instanceof ListShape || $shape instanceof MapShape) {
-                $body = 'MEMBER_CODE';
-                $inputElement = '$this->' . $member->getName();
```
Comment (Nyholm) [inline src/CodeGenerator/src/Generator/RequestSerializer/QuerySerializer.php:73]: Can you tell me why this was removed?

Comment (tyx) [reply src/CodeGenerator/src/Generator/RequestSerializer/QuerySerializer.php:73]: Because as List and Map could be nullable now, we need to go through else statement just below. (to check !== null)

Comment (Nyholm) [reply src/CodeGenerator/src/Generator/RequestSerializer/QuerySerializer.php:73]: Ah, Thank you
