### PR TITLE
Validate request input

### LINKED ISSUE #26: Throw exception if not all require parameters exists in a request object
This should not be valid: 
```php
$input = new \AsyncAws\S3\Input\GetObjectRequest();
$input->setBucket('bref-example');
$result = $s3->getObject($input);
```

Currently it will be a "listObject", which is way wrong..

### PR DESCRIPTION
**Pull request by Nyholm**
This will fix #26. 

There is an issue with this. 

If you do a `PutObjectAclRequest` we validate all required parameters (['Bucket', 'Key']). But you could pass an `AccessControlPolicy` which have a list of `Grant`. Each `Grant` has a `Grantee` which has one required parameter ('$Type'). We never validate `$Type` since `AccessControlPolicy` is not required. 

This is a minor thing but I think it should be documented.

### CODE REVIEW

File: src/Core/AbstractApi.php [hunk 1]
```diff
@@ -135,4 +135,28 @@ protected function getEndpoint(string $uri, array $query):?string
...
+            // There is nothing we can do
+            return;
+        }
+        $requirements = \constant($class . '::REQUIRED_PARAMETERS');
+        if (!\is_array($requirements)) {
+            throw new InvalidArgument(sprintf('Constant "" must be an array.', $class . '::REQUIRED_PARAMETERS'));
+        }
+
+        foreach ($requirements as $name) {
+            $method = 'get' . $name;
```
Comment (jderusse) [inline src/Core/AbstractApi.php]: this could be faster at runtime if we generate a method `isValid()`. 

By implementing the logic here we performs a lot of function call and logic that could have been done when generating the file.

WDYT?

Comment (Nyholm) [reply src/Core/AbstractApi.php]: I was first planning to have an `AbstractInput` with an `isValid()` function to do these checks. But I changed my mind since I didnt feel like creating a new class =).

Comment (Nyholm) [reply src/Core/AbstractApi.php]: I'll make sure to generate these.

**Comment by Nyholm** [comment]
PR is updated

File: src/S3/Input/CopyObjectRequest.php [hunk 2]
```diff
@@ -859,4 +861,17 @@ public function requestUri(): string
...
     }
+
+    public function validate(): void
+    {
+        foreach (['Bucket', 'CopySource', 'Key'] as $name) {
+            if (null === $value = $this->$name) {
+                throw new InvalidArgument(sprintf('Missing parameter "%s" when validating the "%s". The value cannot be null.', $name, __CLASS__));
+            }
+
+            if (\is_object($value) && method_exists($value, 'validate')) {
```
Comment (jderusse) [inline src/S3/Input/CopyObjectRequest.php]: that could be guessed at build time isn't it?

File: src/S3/Input/CopyObjectRequest.php [hunk 3]
```diff
@@ -859,4 +861,17 @@ public function requestUri(): string
 
         return "/{$uri['Bucket']}/{$uri['Key']}";
     }
+
+    public function validate(): void
+    {
+        foreach (['Bucket', 'CopySource', 'Key'] as $name) {
+            if (null === $value = $this->$name) {
+                throw new InvalidArgument(sprintf('Missing parameter "%s" when validating the "%s". The value cannot be null.', $name, __CLASS__));
```
Comment (jderusse) [inline src/S3/Input/CopyObjectRequest.php]: Shouldn't we add the className? When validating a sub-object, the name of the parameter could be meaningless

File: src/S3/Input/CopyObjectRequest.php (hunk 2 above)
Comment (Nyholm) [reply src/S3/Input/CopyObjectRequest.php]: Could.. but it is a bit tricky.. I rather leave that for a future improvement.

File: src/S3/Input/CopyObjectRequest.php (hunk 3 above)
Comment (Nyholm) [reply src/S3/Input/CopyObjectRequest.php]: We are using `__CLASS__ `. Is there need for something more?

File: build/Generator/ApiGenerator.php [hunk 4]
```diff
@@ -217,6 +220,23 @@ private function generateInputClass(string $service, string $operationName, stri
             $this->inputClassRequestGetters($inputShape, $class, $operationName);
         }
 
+        // Add validate()
+        $namespace->addUse(InvalidArgument::class);
+        $requiredArray = '\'' . implode("', '", $requiredProperties) . '\'';
+
+        $validateBody = <<<PHP
```
Comment (jderusse) [inline build/Generator/ApiGenerator.php]: whats about?
```php
foreach ($requiredProperties as $property) {
   $validateBody.= "if (null === \$this->$property) throw ...;";
   if ($defintions[$property]['type'] === 'struct') {
     $validateBody.=' \$this->$property->validate();";
   }
}

File: src/S3/Input/CopyObjectRequest.php (hunk 3 above)
Comment (jderusse) [reply src/S3/Input/CopyObjectRequest.php]: nvm.. sorry for the noise

File: build/Generator/ApiGenerator.php (hunk 4 above)
Comment (Nyholm) [reply build/Generator/ApiGenerator.php]: Oh, that is correct. I was looking to figure things out in the return type. 

I'll give it a try

Comment (Nyholm) [reply build/Generator/ApiGenerator.php]: Fixed it!

**Comment by Nyholm** [comment]
The issue I described in the initial comment is not fixed.

File: src/S3/Input/AccessControlPolicy.php [hunk 5]
```diff
@@ -56,4 +56,14 @@ public function setOwner(?Owner $value): self
...
+
+    public function validate(): void
+    {
+        foreach ($this->Grants as $item) {
+            $item->validate();
+        }
+        if ($this->Owner) {
+            $this->Owner->validate();
+        }
+    }
```
Comment (Nyholm) [inline src/S3/Input/AccessControlPolicy.php]: Here we validate `Grants` and `Owner` even though they are not required. 

So, if they exist, they have to be valid.

Comment (jderusse) [reply src/S3/Input/AccessControlPolicy.php]: good catch

**Comment by jderusse** [comment]
thank you

**Comment by Nyholm** [comment]
Thank you for the reviews and suggestions
