### PR TITLE
Make sure we dont throw exception twice

### LINKED ISSUE #171: Dont throw exception twice
If an exception is thrown on `->resolve()`, it can be caught. But then on `__destruct()`, we will call resolve again and a new message is thrown.

### PR DESCRIPTION
**Pull request by Nyholm**
This will fix #171

### CODE REVIEW

File: src/Core/Result.php [hunk 1]
```diff
@@ -41,6 +41,14 @@ class Result
      */
     private $httpClient;
 
+    /**
+     * A Result can be resolved many times. This boolean is true if the result
+     * has been resolved at least once.
+     *
+     * @var bool
+     */
+    private $isResolved = false;
```
Comment (jderusse) [inline src/Core/Result.php]: could be returned in `info()` too

Comment (Nyholm) [reply src/Core/Result.php]: Good idea!
