### PR TITLE
Fixed issue with exception generation

### LINKED ISSUE #1264: Timestream error 500 can trigger `ErrorException` when building `InternalServerException`
```
ErrorException Undefined array key "message" 
    vendor/voxie/async-aws-timestream-write/src/Exception/InternalServerException.php:17 Illuminate\Foundation\Bootstrap\HandleExceptions::handleError
    vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:257 Illuminate\Foundation\Bootstrap\HandleExceptions::Illuminate\Foundation\Bootstrap\{closure}
    vendor/voxie/async-aws-timestream-write/src/Exception/InternalServerException.php:17 AsyncAws\TimestreamWrite\Exception\InternalServerException::populateResult
    vendor/voxie/async-aws-core/src/Exception/Http/HttpExceptionTrait.php:50 AsyncAws\Core\Exception\Http\ClientException::__construct
    vendor/voxie/async-aws-core/src/Response.php:406 AsyncAws\Core\Response::AsyncAws\Core\{closure}
    vendor/voxie/async-aws-core/src/Response.php:423 AsyncAws\Core\Response::getResolveStatus
    vendor/voxie/async-aws-core/src/Response.php:123 AsyncAws\Core\Response::resolve
    vendor/voxie/async-aws-core/src/Response.php:105 AsyncAws\Core\Response::__destruct
```

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Strictly speaking, this is a spec compliance bug with the server-side implementations, but getting Amazon to anything is impossible. Fixes #1264.

### CODE REVIEW

File: src/CodeGenerator/src/Definition/StructureMember.php [hunk 1]
```diff
@@ -22,6 +22,10 @@ public function getOwnerShape(): StructureShape
 
     public function isRequired(): bool
     {
+        if ($this->getOwnerShape() instanceof ExceptionShape && \in_array(strtolower($this->data['_name']), ['code', 'message'], true)) {
```
Comment (jderusse) [inline src/CodeGenerator/src/Definition/StructureMember.php:25]: Looking at generated code, it looks like all occurrences are `messages` (code is never required)

**Review by jderusse — APPROVED** [review]
I think thats the best move we can do :(

Is it a BC break to have a null value for message? Shouldn't we fallback to something else (ie. `?? ''`) ?

File: src/CodeGenerator/src/Definition/StructureMember.php (hunk 1 above)
Comment (GrahamCampbell) [reply src/CodeGenerator/src/Definition/StructureMember.php:25]: I think this is only because of what we have currently generated. I think in principal newly generated options could use code. I copied what was done for `isNullable`.

**Comment by GrahamCampbell** [comment]
> Is it a BC break to have a null value for message? Shouldn't we fallback to something else (ie. ?? '') ?

I don't think we're breaking anything. If we decide to skip setting message, it is already set to `''`.

**Comment by jderusse** [comment]
thank you
