### PR TITLE
#2024 - Fixed deprecation warning for DateTimeInterface::RFC7231

### LINKED ISSUE #2024: Deprecated constant in PHP 8.5 `DateTimeInterface::RFC7231`
```
Deprecated: Constant DateTimeInterface::RFC7231 is deprecated since 8.5, as this format ignores the associated timezone and always uses GMT
```

I'll post a PR in a bit

The RFC7231 format outputs `D, d M Y H:i:s \G\M\T` which hardcodes "GMT" instead of using the actual timezone, making it semantically incorrect.

### Code Generator (root cause)
- `src/CodeGenerator/src/Generator/InputGenerator.php` (lines 598-603)
  - Converts RFC822 format to RFC7231 for header timestamps
  - Generates code using `\DateTimeInterface::RFC7231`

### Generated S3 Input Files (13 usages)
- `src/Service/S3/src/Input/DeleteObjectRequest.php:271`
- `src/Service/S3/src/Input/AbortMultipartUploadRequest.php:181`
- `src/Service/S3/src/Input/CopyObjectRequest.php:1170, 1176`
- `src/Service/S3/src/Input/HeadObjectRequest.php:469, 475, 525`
- `src/Service/S3/src/Input/GetObjectRequest.php:504, 510, 560`
- `src/Service/S3/src/Input/UploadPartCopyRequest.php:471, 477`

## Solution

Replace the deprecated `\DateTimeInterface::RFC7231` constant with `\DateTimeInterface::RFC1123`

This approach:
- Maintains backward compatibility with PHP 8.1+
- Produces identical output to the deprecated constant
- Eliminates the deprecation warning in PHP 8.5+
- No behavioral changes

### PR DESCRIPTION
**Pull request by deluxetom**
* Resolves #2024

Fix PHP 8.5 deprecation warning for `DateTimeInterface::RFC7231` constant by using `RFC1123` instead.

### CODE REVIEW

File: src/CodeGenerator/src/Generator/InputGenerator.php [hunk 1]
```diff
@@ -597,7 +597,8 @@ private function stringify(string $variable, Member $member, string $part): stri
 
                 if ('RFC822' === $format) {
                     $variable .= '->setTimezone(new \\DateTimeZone("GMT"))';
-                    $format = 'RFC7231';
+                    // Use RFC1123 instead of deprecated RFC7231 constant (PHP 8.5+)
```
Comment (jderusse) [inline src/CodeGenerator/src/Generator/InputGenerator.php]: `\DateTimeInterface::RFC1123` is identical to `\DateTimeInterface::RFC822`.
Which encodes GMT's timezone in `+0000` and was an issue for `MinIO `(https://github.com/async-aws/aws/issues/1213)

We used `RFC7231` instead of `RFC822` in a similar way to the official PHP sdk.

If the constant is deprecated, then I suggest returning `$variable . '->format(\'D, d M Y H:i:s \G\M\T\')';`

File: src/Service/S3Vectors/src/Enum/DataType.php [hunk 2]
```diff
@@ -5,7 +5,11 @@
 final class DataType
 {
     public const FLOAT_32 = 'float32';
+    public const UNKNOWN_TO_SDK = 'UNKNOWN_TO_SDK';
```
Comment (jderusse) [inline src/Service/S3Vectors/src/Enum/DataType.php:8]: We be fixed in a dedicated PR #2026

File: src/CodeGenerator/src/Generator/InputGenerator.php (hunk 1 above)
Comment (deluxetom) [reply src/CodeGenerator/src/Generator/InputGenerator.php]: ok, I can do that

**Comment by jderusse** [comment]
could you please rebase your PR, to fix issue with `s3vectors`

**Comment by jderusse** [comment]
thank you @deluxetom
